name: ui
description: Shared UI Components, Widgets, Fonts, Colors and Theme
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.29.0"

# https://dart.dev/tools/pub/workspaces
resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  collection: ^1.19.1
  #google_fonts:

dev_dependencies:
  # Test
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
